import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//* import comps
import PageHeader from '../components/PageHeader'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Learne</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://alexbeciana.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/profile-pic.png" alt="Abeciana Logo" width={32} height={32} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
